services:
  adamed:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adamed-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ENV BASEPATH=
      - NPM_CONFIG_LEGACY_PEER_DEPS=true
    restart: unless-stopped
    # Add volumes if you need to persist data
    # volumes:
    #   - ./data:/app/data
    networks:
      - adamed-network

networks:
  adamed-network:
    driver: bridge

# volumes:
#   postgres_data: