version: '3.8'

services:
  dreamspos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dreamspos-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BASEPATH=${BASEPATH:-""}
    restart: unless-stopped
    # Add volumes if you need to persist data
    # volumes:
    #   - ./data:/app/data
    networks:
      - dreamspos-network

# For development environment, you might want to add services like a database
# Example:
#   db:
#     image: postgres:14
#     container_name: dreamspos-db
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=dreamspos
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - dreamspos-network

networks:
  dreamspos-network:
    driver: bridge

# volumes:
#   postgres_data: